version: 2.1
jobs:
  build:
    macos:
      xcode: 9.2
    steps:
    - checkout
    - run:
        name: Build the app
        command: script/build
    - store_artifacts:
        path: publish/
workflows:
  version: 2.1
  workflow:
    jobs:
    - build


